# Generated by Django 5.2.4 on 2025-07-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Salary', 'Salary'), ('Bills', 'Bills'), ('Transport', 'Transport'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
